### ISSUE TITLE
Sample 45

### ISSUE THREAD

**Issue by anasram** [takahashim/epub-check-test#2]
What's wrong with Sample 45?

I have the same problem. Why a `text/css` file might need a fallback?

**Comment by takahashim** [comment]
@anasram the problem in sample045 is that `id:style` (`css/stylesheet.css`) is in spine, so reading system should use it as contents to read.  But `text/css` is not EPUB Core Media Types, so it needs fallback chain.

**Comment by anasram** [comment]
> But `text/css` is not EPUB Core Media Types, so it needs fallback chain.

See EPUB Core Media Types table [here](http://www.idpf.org/epub/30/spec/epub30-publications.html#sec-core-media-types). It considers `text/css` as an EPUB core media type.

**Comment by takahashim** [comment]
Oh, sorry. I should quote from http://www.idpf.org/epub/30/spec/epub30-publications.html#sec-itemref-elem

> Each referenced manifest item must be either a) an EPUB Content Document or b) another type of Publication Resource which, regardless of whether it is a Core Media Type Resource or a Foreign Resource, must include an EPUB Content Document in its fallback chain.
